# Homebrew formula for GitRoll 0.3.0 (macOS and Linux).
# Generated by scripts/release.mjs; don't edit the generated gitroll.rb by hand.
class Gitroll < Formula
  desc "Private logbook stored in your own Git repository"
  homepage "https://github.com/jimhoyd-com/gitroll"
  url "https://github.com/jimhoyd-com/gitroll/releases/download/v0.3.0/gitroll-0.3.0.tgz"
  sha256 "b19ad539bfee90193eb8f31f20c3039bb1fbedc55e3e3f2921478a1535f638f1"
  license "MIT"

  depends_on "git"
  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    ENV["GITROLL_HOME"] = testpath/"settings"
    ENV["GITROLL_ROLLS"] = testpath/"rolls"
    ENV["GIT_AUTHOR_NAME"] = ENV["GIT_COMMITTER_NAME"] = "Homebrew"
    ENV["GIT_AUTHOR_EMAIL"] = ENV["GIT_COMMITTER_EMAIL"] = "brew@example.com"
    system bin/"gitroll", "new", "Brew Test"
    assert_match "Logged", shell_output("#{bin}/gitroll log 'Installed with Homebrew'")
    assert_match "Installed with Homebrew", shell_output("#{bin}/gitroll find Homebrew")
    assert_match "looks good", shell_output("#{bin}/gitroll check")
  end
end
