# Homebrew formula for GitRoll 0.5.0 (macOS and Linux).
# Generated by scripts/release.mjs; don't edit the generated gitroll.rb by hand.
class Gitroll < Formula
  desc "Private logbook stored in your own Git repository"
  homepage "https://github.com/jimhoyd-com/gitroll"
  url "https://github.com/jimhoyd-com/gitroll/releases/download/v0.5.0/gitroll-0.5.0.tgz"
  sha256 "5d4c16d9d80a39db7927e75515ba8fc0a17624373e3ee871790645ec846534ac"
  # PolyForm Shield 1.0.0 (source available). It has no SPDX identifier, and
  # Homebrew's convention for a license it cannot express in SPDX is this.
  license :cannot_represent

  depends_on "git"
  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    ENV["GITROLL_HOME"] = testpath/"settings"
    ENV["GITROLL_ROLLS"] = testpath/"rolls"
    ENV["GIT_AUTHOR_NAME"] = ENV["GIT_COMMITTER_NAME"] = "Homebrew"
    ENV["GIT_AUTHOR_EMAIL"] = ENV["GIT_COMMITTER_EMAIL"] = "brew@example.com"
    system bin/"gitroll", "new", "Brew Test"
    assert_match "Logged", shell_output("#{bin}/gitroll log 'Installed with Homebrew'")
    assert_match "Installed with Homebrew", shell_output("#{bin}/gitroll find Homebrew")
    assert_match "looks good", shell_output("#{bin}/gitroll check")
  end
end
